# Generated by Django 6.0.5 on 2026-05-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='emission_factor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='facility_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='source_type',
            field=models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'Utility'), ('TRAVEL', 'Travel')], max_length=50),
        ),
    ]
