# Generated by Django 6.0.5 on 2026-05-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_emissionrecord_emission_factor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionrecord',
            name='emission_factor',
        ),
        migrations.RemoveField(
            model_name='emissionrecord',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='emissionrecord',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='facility_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='source_type',
            field=models.CharField(choices=[('SAP', 'SAP'), ('Utility', 'Utility'), ('Travel', 'Travel')], default='SAP', max_length=20),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
